version: '3.4'

services:
#SQL SERVER
  db:
    image: "microsoft/mssql-server-windows-developer:2017-latest" 
    environment:      
      SA_PASSWORD: "Loans@123"
      ACCEPT_EULA: "Y"
    ports:
       - "1433:1433"
#API
  invilla.api:
    image: ${DOCKER_REGISTRY-}invillaapi
    build:
      context: .
      dockerfile: Invilla.API\Dockerfile      
    depends_on:
       - db
    ports:
       - "5000:80"
       - "5001:443"
    links:
       - db